# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_announcement_spartan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.CharField(max_length=500, null=True, verbose_name='Announcement description'),
        ),
    ]
