# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-28 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spartan',
            name='bank_account',
        ),
        migrations.AddField(
            model_name='spartan',
            name='bank',
            field=models.CharField(max_length=30, null=True, verbose_name='Bank account'),
        ),
        migrations.AlterField(
            model_name='spartan',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Date FORMAT YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='spartan',
            name='cnp',
            field=models.IntegerField(null=True, verbose_name='CNP'),
        ),
        migrations.AlterField(
            model_name='spartan',
            name='cui',
            field=models.CharField(max_length=30, null=True, verbose_name='CUI'),
        ),
        migrations.AlterField(
            model_name='spartan',
            name='series',
            field=models.CharField(max_length=30, null=True, verbose_name='ID card series'),
        ),
    ]
