# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spartans', '0003_auto_20160701_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spartan',
            name='cnp',
            field=models.CharField(max_length=20, null=True, verbose_name='CNP'),
        ),
    ]
