# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('text', models.CharField(max_length=500, null=True)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('country', models.TextField(max_length=50, null=True)),
                ('city', models.TextField(max_length=100, null=True)),
                ('data', models.DateField(null=True, verbose_name='Task-ul trebuie indeplinit in data de')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('timePost', models.TimeField(null=True, verbose_name='Ora')),
                ('category', models.CharField(max_length=20, null=True)),
                ('money', models.IntegerField(null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'creation_date',
            },
        ),
    ]
