# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='adress',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
