# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='path',
            new_name='path_banner',
        ),
        migrations.AddField(
            model_name='category',
            name='path_bg',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
