# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0002_announcement_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
