# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0002_auto_20160421_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path_icon',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
