# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0003_announcement_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='creation_date',
            field=models.DateField(null=True, verbose_name='Task-ul trebuie indeplinit in data de '),
        ),
    ]
