# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0004_auto_20160319_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='time',
            field=models.TimeField(null=True, verbose_name='QQQ'),
        ),
    ]
