# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0006_auto_20160319_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='categoriy',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
