# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0007_announcement_categoriy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='categoriy',
            new_name='category',
        ),
        migrations.AddField(
            model_name='announcement',
            name='city',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='country',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
