# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0008_auto_20160323_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='adress',
            new_name='address',
        ),
    ]
