# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0009_auto_20160325_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='creation_date',
            field=models.DateField(null=True, verbose_name='Task-ul trebuie indeplinit in data de'),
        ),
    ]
