# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0010_auto_20160330_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='data',
            field=models.DateField(null=True, verbose_name='Task-ul trebuie indeplinit in data de'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
