# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0011_auto_20160402_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='money',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
