# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractions', '0012_announcement_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='money',
            field=models.IntegerField(null=True),
        ),
    ]
