# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-01 14:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9223372036854775807), django.core.validators.MinValueValidator(1)])),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
