# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-31 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='posts.Announcement'),
        ),
    ]
