# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('useractions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pret', models.IntegerField(null=True)),
                ('tip', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferte', to='useractions.Announcement')),
                ('spartan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spartan', to='authentication.Spartan')),
            ],
        ),
    ]
