# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-21 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '__first__'),
        ('spartans', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='posts.Announcement')),
                ('spartan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='spartans.Spartan')),
            ],
        ),
    ]
