# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding', '0002_offer_post'),
        ('spartans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='spartan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='spartans.Spartan'),
        ),
    ]
