# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_auto_20160621_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='posts.Announcement'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='spartan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='spartan.Spartan'),
        ),
    ]
