# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_auto_20160430_1038'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useractions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='useractions.Announcement')),
                ('message', models.CharField(max_length=1000, null=True)),
                ('data', models.DateField(null=True, verbose_name='Data publicarii review-ului')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='authentication.Spartan')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
