# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20160623_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='creation_date',
        ),
    ]
