# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_remove_review_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 6, 30, 7, 13, 55, 767127, tzinfo=utc), null=True, verbose_name='Review publication day'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.CharField(max_length=1000, null=True, verbose_name='Review message'),
        ),
    ]
