# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 05:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20160630_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 7, 1, 5, 36, 11, 807277, tzinfo=utc), null=True, verbose_name='Review publication day'),
        ),
    ]
