# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20160702_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 7, 2, 9, 24, 8, 478331, tzinfo=utc), null=True, verbose_name='Review publication day'),
        ),
    ]
