# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-01 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20160701_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 7, 1, 7, 3, 39, 759057, tzinfo=utc), null=True, verbose_name='Review publication day'),
        ),
    ]
