# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20160702_0935'),
        ('review', '0007_auto_20160706_0729'),
    ]

    operations = [
    ]
