# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0013_auto_20160708_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 7, 8, 9, 25, 50, 314009, tzinfo=utc), null=True, verbose_name='Review publication day'),
        ),
    ]
