# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactUS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
