# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 07:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=36, null=True)),
                ('telefon', models.IntegerField(null=True)),
                ('cod', models.CharField(blank=True, max_length=100, null=True)),
                ('sold', models.IntegerField(default=0)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Spartan',
            fields=[
                ('nume', models.CharField(max_length=40)),
                ('prenume', models.CharField(max_length=40)),
                ('data_nasterii', models.DateField(null=True, verbose_name='Data nasterii')),
                ('address', models.CharField(max_length=500, null=True)),
                ('cnp', models.IntegerField(null=True)),
                ('serie', models.CharField(max_length=30, null=True)),
                ('cui', models.CharField(max_length=30, null=True)),
                ('contBancar', models.CharField(max_length=30, null=True)),
                ('abilitate1', models.CharField(max_length=20, null=True)),
                ('abilitate2', models.CharField(blank=True, max_length=20, null=True)),
                ('abilitate3', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('spartanStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
