# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(null=True, upload_to='/images/'),
        ),
    ]
