# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Skills',
        ),
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='photo',
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=40),
        ),
    ]
