# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-21 09:02
from __future__ import unicode_literals

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20160721_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=authentication.models.upload_location, width_field='width_field'),
        ),
    ]
