# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20160319_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/avatars', verbose_name='profile picture'),
        ),
    ]
