# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_account_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='descriere',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
