# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20160407_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='photo',
        ),
    ]
