# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_account_descriere'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='descriere',
            field=models.CharField(blank=True, max_length=244),
        ),
    ]
