# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_account_descriere'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
