# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_account_cod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='descriere',
        ),
    ]
