# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_spartan'),
    ]

    operations = [
        migrations.AddField(
            model_name='spartan',
            name='SpartanStatus',
            field=models.BooleanField(default=False),
        ),
    ]
