# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_account_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spartan',
            name='contBancar',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spartan',
            name='cui',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='spartan',
            name='serie',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
