# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20160417_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spartan',
            name='abilitate2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spartan',
            name='abilitate3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
