# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-01 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000, null=True, verbose_name='Review message')),
                ('data', models.DateField(default=datetime.datetime(2016, 8, 1, 14, 58, 46, 88618, tzinfo=utc), null=True, verbose_name='Review publication day')),
            ],
        ),
        migrations.CreateModel(
            name='UrlUnique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un_hash', models.CharField(max_length=33, unique=True, verbose_name='Url')),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
    ]
