# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20160722_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 7, 25, 7, 12, 13, 595790, tzinfo=utc), null=True, verbose_name='Review publication day'),
        ),
    ]
