# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-01 17:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20160801_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 8, 1, 17, 42, 52, 543012, tzinfo=utc), null=True, verbose_name='Review publication day'),
        ),
    ]
