# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20160725_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='data',
            field=models.DateField(default=datetime.datetime(2016, 7, 25, 7, 21, 15, 748130, tzinfo=utc), null=True, verbose_name='Review publication day'),
        ),
    ]
