# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-01 14:58
from __future__ import unicode_literals

import authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=authentication.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='authentication.Country'),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='authentication.City'),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='authentication.Country'),
        ),
    ]
