# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-21 12:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.CharField(blank=True, max_length=90000)),
                ('not_type', models.CharField(default=b'', max_length=20)),
                ('seen', models.BooleanField(default=False)),
                ('url', models.CharField(default=b'', max_length=1000)),
                ('id_hash', models.CharField(default=b'', max_length=10000)),
                ('context', models.CharField(blank=True, default=b'', max_length=10000)),
                ('receiver', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
