# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-21 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='context',
            field=models.CharField(default=b'', max_length=10000),
        ),
    ]
